spring.application.name=realtime-notification
server.port=8080
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:63342,http://localhost:5173,http://localhost:5174}
spring.websocket.enabled=true
spring.websocket.message-broker.enabled=true

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.level.com.notification=DEBUG
logging.level.org.springframework.web.socket=DEBUG

# ===============================
# Redis Configuration
# ===============================

spring.data.redis.host=${REDIS_HOST:98.80.186.221}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:Makhsodur123}

# Connection pool (Lettuce)
spring.redis.lettuce.pool.max-active=10
spring.redis.lettuce.pool.max-idle=5
spring.redis.lettuce.pool.min-idle=1

# Timeout (milliseconds)
spring.redis.timeout=60000

##########################################################
#                     Kafka Config                       #
##########################################################
#spring.kafka.bootstrap-servers=localhost:29092
#
## Consumer settings
#spring.kafka.consumer.group-id=my-group
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#
## Producer settings
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


